services:  
  opentelemetry-collector:
    image: otel/opentelemetry-collector:0.77.0
    restart: unless-stopped
    networks:
      - grafanet
    ports:
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
    command: --config=/etc/opentelemetry-collector/config.yaml
    depends_on:
      - grafana
      - tempo
      - mimir
    volumes:
      - ./config/opentelemetry-collector:/etc/opentelemetry-collector

  tempo:
    image: grafana/tempo:latest
    restart: unless-stopped
    networks:
      - grafanet
    volumes:
      - ./config/tempo:/etc/tempo/
    command: ["-config.file=/etc/tempo/config.yaml"]

  mimir:
    image: grafana/mimir:latest
    restart: unless-stopped
    networks:
      - grafanet
    volumes:
      - ./config/mimir:/etc/mimir
    command: ["--config.file=/etc/mimir/config.yaml"]

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    networks:
      - grafanet
    ports:
      - 8080:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_TRACING_OPENTELEMETRY_OTLP_ADDRESS=opentelemetry-collector:4317
      - GF_TRACING_OPENTELEMETRY_OTLP_PROPAGATION=w3c
      - GF_FEATURE_TOGGLES_ENABLE=tempoBackendSearch,tempoSearch,tempoServiceGraph
    volumes:
      - ./config/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    depends_on:
      - mimir
      - tempo

networks:
  grafanet:
    driver: bridge
    name: grafanet